config/routes.rb
Rails.application.routes.draw do

 

  # %w[about privacy terms].each do |page|
  # 	get page, controller: "info", action: page
  # end

  devise_for :admins, 
  	controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}, 
  	:path => 'profile', 
  	:path_names => {:sign_in => 'login', 
  					:sign_out => 'logout', 
  					:sign_up => "signup"}
	resources :beers do 
		collection do 
			get 'search'
		end
		resources :reviews, except: [:show, :index]
		resource :like, module: :beers
	end	

  get "sitemap" => "beers#sitemap"

	root 'beers#index'
  resources :pages, path: '', only: [:show]
  get '*path' => redirect('/')

end

app/views/pages/_form.html.erb
<%= form_for @page, html: { multipart: true } do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: "srt" %><br>
    <%= f.text_field :name, placeholder: :name %>
  </div>

  <div class="field">
    <%= f.label :content, class: "srt" %><br>
    <%= f.text_area :content, placeholder: :content %>
  </div>

  <div class="actions">
    <%= f.submit "Publish" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="skinny_wrapper">

	<h1>Editing Page</h1>
	<%= render 'form' %>
</div>

app/views/pages/index.html.erb
<div class="skinny_wrapper">
  <h1>Listing Pages</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.name %></td>
          <td><%= page.content %></td>
          <td><%= link_to 'Show', page %></td>
          <td><%= link_to 'Edit', edit_page_path(page) %></td>
          <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Page', new_page_path %>
</div>

app/views/pages/new.html.erb
<div class="skinny_wrapper">
	<h1>New Page</h1>
	<%= render 'form' %>
</div>
<br><br>

app/views/pages/show.html.erb
<div class="skinny_wrapper">
	<h1><%= @page.name %></h1>
	<%= markdown @page.content %>
</div>