config/routes.rb
Rails.application.routes.draw do

 

  # %w[about privacy terms].each do |page|
  # 	get page, controller: "info", action: page
  # end

  devise_for :admins, 
  	controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}, 
  	:path => 'profile', 
  	:path_names => {:sign_in => 'login', 
  					:sign_out => 'logout', 
  					:sign_up => "signup"}
	resources :beers do 
		collection do 
			get 'search'
		end
		resources :reviews, except: [:show, :index]
		resource :like, module: :beers
	end	

  get "sitemap" => "beers#sitemap"

	root 'beers#index'
  resources :pages, path: '', only: [:show]
  get '*path' => redirect('/')

end

app/models/beer.rb
class Beer < ActiveRecord::Base
	belongs_to :admin
	has_many :reviews
	has_many :likes
	searchkick

	has_attached_file :image, styles: { medium: "600x400#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	extend FriendlyId
  	friendly_id :name, use: :slugged

  	def should_generate_new_friendly_id?
		slug.blank? || name_changed?
	end

	def self.get_previous_beer(current_beer)
    	Beer.where("beers.id < ? ", current_beer.id).order('created_at asc').last
    end

	def self.get_next_beer(current_beer)
        Beer.where("beers.id > ? ", current_beer.id).order('created_at asc').first
    end

    

end

app/controllers/beers/likes_controller.rb
class Beers::LikesController < ApplicationController
 	before_action :authenticate_admin!
 	before_action :set_beer

	def create
		@beer.likes.where(admin_id: current_admin.id).first_or_create

		respond_to do |format|
	      format.html { redirect_to @beer }
	      format.js
		end
	end

	def destroy
		@beer.likes.where(admin_id: current_admin.id).destroy_all

		respond_to do |format|
		      format.html { redirect_to @beer }
		      format.js
		end
	end

	private

	def set_beer 
		@beer = Beer.friendly.find(params[:beer_id])
	end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy, :like]
  before_action :authenticate_admin!, except: [:index, :show, :search, :sitemap]

  def search
    if params[:search].present?
      @beers = Beer.search(params[:search])
    else
      @beers = Beer.all
    end
  end

  def index
    @beers = Beer.order("created_at desc").paginate(page: params[:page], per_page: 9)
        prepare_meta_tags title: "Beers", 
              description: "Tasted beers by Beerdid",
              og: {
              title: "Beers",
              description: "Tasted beers by Beerdid",
            },
              twitter: {
              description: "Tasted beers by Beerdid"
            }
  end

  def show
    @reviews = Review.where(beer_id: @beer.id).order("created_at DESC")
    prepare_meta_tags(title: @beer.name,
                      description: @beer.description.truncate(120),
                      image: @beer.image.url(:original),
                      og: {
                          title: @beer.name,
                          description: @beer.description.truncate(120),
                          image: @beer.image.url(:original)
                      },
                      twitter: {
                          description: @beer.description.truncate(120),
                          image: @beer.image.url(:original)
                      }
            )

      @avg_review = @reviews.average(:rating)
    
  end

  def new
    if current_admin.admin?
      @beer = current_admin.beers.build
    else
      redirect_to root_path
    end
  end

  def edit
    if current_admin.admin?
    else
      redirect_to root_path
    end
  end

  def create
    @beer = current_admin.beers.build(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @beer.update(beer_params) 
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_admin.admin?
      @beer.destroy
      respond_to do |format|
        format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path
    end
  end

  def like
    if @beer.liked_by current_admin
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def sitemap
      @beers = Beer.all
      @pages = Page.all
      respond_to do |format|
          format.xml { render layout: false }
      end
  end


  private
    def set_beer
      @beer = Beer.friendly.find(params[:id])
    end

    def beer_params
      params.require(:beer).permit(:name, :description, :style, :abv, :ibu, :brewery, :location, :image, :slug, :youtube_url, :rate_beer, :beer_advocate)
    end
end

app/helpers/beers_helper.rb
module BeersHelper


  def embed(youtube_url)
  	if !@beer.youtube_url.blank?
    	youtube_id = @beer.youtube_url.split("=").last
    	content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
	end
  end


end

app/views/beers/_form.html.erb
<%= form_for [@beer], html: { multipart: true } do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :youtube_url, class: "srt" %><br>
    <%= f.text_field :youtube_url, placeholder: :youtube_url %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
<br>
  <div class="field">
    <%= f.label :name, class: "srt" %><br>
    <%= f.text_field :name, placeholder: :name %>
  </div>
  <div class="field">
    <%= f.label :description, class: "srt" %><br>
    <%= f.text_area :description, placeholder: :description %>
  </div>
  <div class="field">
    <%= f.label :style, class: "srt" %><br>
    <%= f.text_field :style, placeholder: :style %>
  </div>
  <div class="field">
    <%= f.label :abv, class: "srt" %><br>
    <%= f.text_field :abv, placeholder: :abv %>
  </div>
  <div class="field">
    <%= f.label :ibu, class: "srt" %><br>
    <%= f.number_field :ibu, placeholder: :ibu %>
  </div>
  <div class="field">
    <%= f.label :brewery, class: "srt" %><br>
    <%= f.text_field :brewery, placeholder: :brewery %>
  </div>
  <div class="field">
    <%= f.label :location, class: "srt" %><br>
    <%= f.text_field :location, placeholder: :location %>
  </div>
  <div class="field">
    <%= f.label :rate_beer, class: "srt" %><br>
    <%= f.text_field :rate_beer, placeholder: :rate_beer %>
  </div>
  <div class="field">
    <%= f.label :beer_advocate, class: "srt" %><br>
    <%= f.text_field :beer_advocate, placeholder: :beer_advocate %>
  </div>

  <div class="actions">
    <%= f.submit "Publish" %>
  </div>
<% end %>

app/views/beers/_likes.html.erb
<% if admin_signed_in? && current_admin.likes?(@beer) %>
  <%= link_to image_tag("beer-full.svg"), beer_like_path(@beer), method: :delete, remote: true, class: 
  "heart" %>
  <div div class="like_count">
  <%= @beer.likes.count %>
</div>
<% else %>
  <%= link_to image_tag("beer-empty.svg"), beer_like_path(@beer), method: :post, remote: true, class: 
  "heart" %>
  <div div class="like_count">
  <%= @beer.likes.count %>
</div>
<% end %>

app/views/beers/edit.html.erb
<div class="skinny_wrapper">
	<h1>Editing Beer</h1>

	<%= render 'form' %>

</div>

app/views/beers/index.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class="homepage_content">
    <% @beers.each do |beer| %>
      <div class="beer">
        <div class="beer_img">
          <%= link_to (image_tag (beer.image.url(:medium))), beer %>
        </div>
        <div class="beer_content">
          <div class="beer_name">
            <h2><%= link_to beer.name, beer %></h2>
          </div>
          <div class="beer_info">
            <p><strong>STYLE:</strong> <%= beer.style %></p>
            <p><strong>BREWERY:</strong> <%= beer.brewery %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= will_paginate @beers %>
</div>
<br>

app/views/beers/new.html.erb
<div class="skinny_wrapper">
	<h1>New Beer</h1>

	<%= render 'form' %>
</div>
<br><br>

app/views/beers/search.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class="homepage_content">
    <% @beers.each do |beer| %>
      <div class="beer">
        <div class="beer_img">
          <%= image_tag beer.image.url(:medium) %>
        </div>
        <div class="beer_content">
          <div class="beer_name">
            <h2><%= link_to beer.name, beer %></h2>
          </div>
          <div class="beer_info">
            <p><strong>STYLE:</strong> <%= beer.style %></p>
            <p><strong>BREWERY:</strong> <%= beer.brewery %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>  

app/views/beers/show.html.erb
<div class="skinny_wrapper">
  <div id="beer_show">
    <h1><%= @beer.name %></h1>
    <div class="embed_youtube">
     <%= embed(@beer.youtube_url) %>
    </div>
    <div class="vid_info clearfix">
      <% unless  @beer.id == Beer.first.id   %>
        <%= link_to 'Previous Beer', Beer.get_previous_beer(@beer), class: "button nav-btn"  %>
      <% end %>
      <% unless  @beer.id == Beer.last.id   %> 
        <%= link_to  'Next Beer', Beer.get_next_beer(@beer), class: "button nav-btn" %>
      <% end %>

      <div class="likes">
        <%= render partial: "likes" %>
      </div> 

    </div>
    <hr>
    <div class="clearfix">
      <div class="description">
        <%= image_tag @beer.image.url %>
      </div>
      <div class="beer_data">
        <p><strong>Brewery:</strong> <%= @beer.brewery %></p>
        <p><strong>Location:</strong> <%= @beer.location %></p>
        <p><strong>STYLE:</strong> <%= @beer.style %></p>
        <p><strong>ABV:</strong> <%= number_to_percentage(@beer.abv, precision: 1) %></p>
        <p><strong>IBU:</strong> <%= @beer.ibu %></p>
        <p><strong>AVG RATING:</strong> 
          <% if @avg_review && @beer.rate_beer && @beer.beer_advocate %>
           <%= ((@avg_review + @beer.rate_beer + @beer.beer_advocate) / 3).round(2) %> / 5</p>
          <% elsif @beer.rate_beer && @beer.beer_advocate %>
            <%= ((@beer.rate_beer + @beer.beer_advocate) / 2).round(2) %> / 5</p>
          <% elsif @beer.rate_beer %>
            <%= @beer.rate_beer%> / 5</p>
          <% elsif @beer.beer_advocate %>
            <%= @beer.beer_advocate%> / 5 </p>
          <% else %>
            0 / 5</p>
          <% end %>
      </div>
    </div> 
    <%= markdown @beer.description %>

     <%= render 'reviews/review' %>
    
    <% if admin_signed_in? && current_admin.try(:admin?) %>
      <div id="admin_links">
        <%= link_to "Edit Beer", edit_beer_path(@beer) %>
        <%= link_to "Delete Beer", beer_path(@beer), method: :delete, data: { confirm: "Are you sure?" } %> 
      </div>  
    <% end %>
  </div>
</div>

<script>
  $('.star-rating').raty({
    starOn: '<%= image_path('star-full.svg') %>',
    starOff: '<%= image_path('star-empty.svg') %>',
    starHalf: '<%= image_path('star-half.svg') %>',
    path: '',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  })
</script>