config/routes.rb
Rails.application.routes.draw do

 

  # %w[about privacy terms].each do |page|
  # 	get page, controller: "info", action: page
  # end

  devise_for :admins, 
  	controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}, 
  	:path => 'profile', 
  	:path_names => {:sign_in => 'login', 
  					:sign_out => 'logout', 
  					:sign_up => "signup"}
	resources :beers do 
		collection do 
			get 'search'
		end
		resources :reviews, except: [:show, :index]
		resource :like, module: :beers
	end	

  get "sitemap" => "beers#sitemap"

	root 'beers#index'
  resources :pages, path: '', only: [:show]
  get '*path' => redirect('/')

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_beer
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.admin_id = current_admin.id
    @review.beer_id = @beer.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @beer, notice: 'Review was successfully created.' }
        format.js
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to beer_path notice: 'Review was successfully updated.' }

      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to beer_path(@beer), notice: 'Review was successfully deleted :(.' }

    end
  end

  private
    def set_beer
      @beer = Beer.friendly.find(params[:beer_id])
    end

    def set_review
      @review = Review.find(params[:id])
    end


    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@beer, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    starOn: '<%= image_path('star-on.png') %>',
    starOff: '<%= image_path('star-off.png') %>',
    starHalf: '<%= image_path('star-half.png') %>',
    path: '',
    scoreName: 'review[rating]'
  })
</script>

app/views/reviews/_review.html.erb
<div id="reviews">
      <div class="review_show">
        <h1 class="review_title">Your Thoughts</h1>
          <% @reviews.each do |review| %>
            <div class="review">
              <div class="star-rating" data-score=<%= review.rating %> ></div>
              <p><small>Reviewed <strong><%= time_ago_in_words(review.created_at) %> ago</strong> by <%= review.admin.user_name %></small>
                <% if review.admin == current_admin %>
                  <%= link_to image_tag("delete.svg") ,beer_review_path(@beer, review), method: :delete, data: { confirm: "Are you sure?" }%>
                <% end %>  
              </p>
              <p><%= markdown review.comment %> 
            </div>
          <% end %>
          <% if admin_signed_in? %>
            <%= simple_form_for [@beer, Review.new] do |f| %>
              <div class="field">
                <div id="star-rating"></div>
              </div>
              <div class="field">
                <%= f.text_area :comment %>
              </div> 
              <br>
              <%= f.submit "Add Review", class: "button"%>
            <% end %>
            <% else %>
            <%= link_to "Log in to leave a review", new_admin_session_path, class: "button review-btn" %>
          <% end %>
      </div>
    </div>

    <script>
  $('#star-rating').raty({
    starOn: '<%= image_path('star-full.svg') %>',
    starOff: '<%= image_path('star-empty.svg') %>',
    starHalf: '<%= image_path('star-half.svg') %>',
    path: '',
    scoreName: 'review[rating]'
  })
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_path(@beer) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_path(@beer) %>