config/routes.rb
Rails.application.routes.draw do

 

  # %w[about privacy terms].each do |page|
  # 	get page, controller: "info", action: page
  # end

  devise_for :admins, 
  	controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}, 
  	:path => 'profile', 
  	:path_names => {:sign_in => 'login', 
  					:sign_out => 'logout', 
  					:sign_up => "signup"}
	resources :beers do 
		collection do 
			get 'search'
		end
		resources :reviews, except: [:show, :index]
		resource :like, module: :beers
	end	

  get "sitemap" => "beers#sitemap"

	root 'beers#index'
  resources :pages, path: '', only: [:show]
  get '*path' => redirect('/')

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="wrapper wrapper_footer clearfix">
		<nav class="center">
			<div class="social">
				<a href="http://www.instagram.com/beerdid" target="_blank" title="Beerdid Instagram"><i class="fa fa-instagram fa-lg"></i></a>
				<a href="https://www.facebook.com/beerdidofficial" target="_blank" title="Beerdid Facebook"><i class="fa fa-facebook-square fa-lg"></i></a>
				<a href="http://www.twitter.com/beerdid" target="_blank" title="Beerdid Twitter"><i class="fa fa-twitter-square fa-lg"></i></a>
			</div>
			<ul>
				<li><%= link_to "About", page_path("about") %></li>
				<li><%= link_to "Terms of Service", page_path("terms-of-service") %></li>
				<li><%= link_to "Privacy", page_path("privacy") %></li>
			</ul>
		</nav>
	</div>
</footer>

<script>
  var nav = responsiveNav(".nav-collapse",{
      jsClass: "js", // String: 'JS enabled' class which is added to  element

  });
</script>

<script type="text/javascript">
    var feed = new Instafeed({
        clientId: '82d1d4f4904648b3a1828ff35f060521',
        get: 'user',
  		userId: '2283554013',
  		limit:"4",
  		accessToken: '<%= ENV["INSTAGRAM_ACCESS_TOKEN"] %>',
        template: '<a href="{{link}}"><img src="{{image}}" /></a>',
        resolution: "low_resolution"
    });
    feed.run();
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71295954-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/layouts/_header.html.erb
  <header id="main_navigation" class="clearfix"> 
    <%= link_to root_path, title: "Beerdid Logo" do %>
      <%= image_tag 'logo.svg', alt: 'Beerdid Logo', class: "logo" %>
    <% end %>

 

    <nav class="nav-collapse">
      <ul class="clearfix">
        <li class="searching">    
          <%= form_tag search_beers_path, method: :get, class: "search-box", role: "search" do %> 
            <p>
              <%= text_field_tag :search, params[:search], id: "search" %>
              <%= button_tag(type: "submit", class: "icon", id: "search") do %>
                 <i class="fa fa-search"></i>
              <% end %>
            </p>
            <% end %>
<!--           <form class="search-box" role="search">
              <input type="search" id="search" placeholder="Search..." />
              <button class="icon"><i class="fa fa-search"></i></button>
          </form> -->

        </li>
        <% if admin_signed_in? && current_admin.try(:admin?) %>
          <li>
              <% if current_admin.image.present? %>
                <%= image_tag current_admin.image, width: 30, class: "user_image" %>
              <% else %>
                <%= image_tag current_admin.avatar_url, width: 30, class: "user_image" %>
              <% end %>
              <strong><%= link_to current_admin.user_name, edit_admin_registration_path(@admin) %></strong></li>
          <li><%= link_to "New Beer", new_beer_path %></li>
          <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
          <li><i class="fa fa-beer"></i><li>
        <% elsif admin_signed_in? %>
          <li>
            <% if current_admin.image.present? %>
              <%= image_tag current_admin.image, width: 30, class: "user_image" %>
            <% else %>
              <%= image_tag current_admin.avatar_url, width: 30, class: "user_image" %>
            <% end %>
            <%= link_to current_admin.user_name, edit_admin_registration_path(@admin) %></li>
          <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_admin_session_path %></li>
          <li><%= link_to "Sign up", new_admin_registration_path, class: "signup-btn" %></li>
        <% end %>
      </ul>
    </nav>  
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if display_meta_tags.present? %>
    <%= display_meta_tags %>
  <% else %>
    <title>BEERDID</title>
  <% end %>  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
  <link rel="alternate" href="http://BEERDID.com" hreflang="en-us" />
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
	<% if notice %>
	   <p class="notice"><%= notice %></p>
	<% elsif alert %>   
       <p class="alert"><%= alert %></p>
    <% end %> 
	<%= yield %>

<%= render 'layouts/footer' %>